#docker-compose -f dc-postgresql.yml up -d
version: "3"

services:
  postgres:
    image: postgres:11.1-alpine
    container_name: postgresql_pepper
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pepper